///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace testme1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The testme recording.
    /// </summary>
    [TestModule("49a4a8a6-1563-4c0b-abe6-042fec337c37", ModuleType.Recording, 1)]
    public partial class Testme : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testme1Repository repository.
        /// </summary>
        public static testme1Repository repo = testme1Repository.Instance;

        static Testme instance = new Testme();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Testme()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Testme Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications\\SYSTRAN.InteractiveTranslator.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications\\SYSTRAN.InteractiveTranslator.exe", "", "C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator.MTranslationOptionsPanel.Background' at 93;15.", repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BackgroundInfo, new RecordItemIndex(1));
            repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.Background.Click("93;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.English' at 62;8.", repo.SYSTRANInteractiveTranslator1.EnglishInfo, new RecordItemIndex(2));
            repo.SYSTRANInteractiveTranslator1.English.Click("62;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrow' at 3;4.", repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrowInfo, new RecordItemIndex(3));
            repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrow.Click("3;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.French' at 72;9.", repo.SYSTRANInteractiveTranslator1.FrenchInfo, new RecordItemIndex(4));
            repo.SYSTRANInteractiveTranslator1.French.Click("72;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrow1' at 5;3.", repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrow1Info, new RecordItemIndex(5));
            repo.SYSTRANInteractiveTranslator.MTranslationOptionsPanel.BtnArrow1.Click("5;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.ElementBd' at 142;12.", repo.SYSTRANInteractiveTranslator1.ElementBdInfo, new RecordItemIndex(6));
            repo.SYSTRANInteractiveTranslator1.ElementBd.Click("142;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator.SomeElement' at 258;46.", repo.SYSTRANInteractiveTranslator.SomeElementInfo, new RecordItemIndex(7));
            repo.SYSTRANInteractiveTranslator.SomeElement.Click("258;46");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello'.", new RecordItemIndex(8));
            Keyboard.Press("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator.Translate' at 26;4.", repo.SYSTRANInteractiveTranslator.TranslateInfo, new RecordItemIndex(9));
            repo.SYSTRANInteractiveTranslator.Translate.Click("26;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1000ms.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='bonjour') on item 'SYSTRANInteractiveTranslator2.MTgtRichTextBox'.", repo.SYSTRANInteractiveTranslator2.MTgtRichTextBoxInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.SYSTRANInteractiveTranslator2.MTgtRichTextBoxInfo, "Text", "bonjour");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator2.PARTClose' at 16;16.", repo.SYSTRANInteractiveTranslator2.PARTCloseInfo, new RecordItemIndex(12));
            repo.SYSTRANInteractiveTranslator2.PARTClose.Click("16;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
