///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The helloproj recording.
    /// </summary>
    [TestModule("a5fa6156-b376-4ef0-b03d-d8876034e79a", ModuleType.Recording, 1)]
    public partial class Helloproj : ITestModule
    {
        /// <summary>
        /// Holds an instance of the helloprojRepository repository.
        /// </summary>
        public static helloprojRepository repo = helloprojRepository.Instance;

        static Helloproj instance = new Helloproj();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Helloproj()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Helloproj Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications\\SystranDictionaryManager.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications\\SystranDictionaryManager.exe", "", "C:\\Program Files (x86)\\SYSTRAN 8 TRANSLATOR\\applications", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.File' at CenterLeft.", repo.SYSTRANDictionaryManager.FileInfo, new RecordItemIndex(1));
            repo.SYSTRANDictionaryManager.File.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.MenuPopup' at 140;12.", repo.SystranDictionaryManager1.MenuPopupInfo, new RecordItemIndex(2));
            repo.SystranDictionaryManager1.MenuPopup.Click("140;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonEditorDropdownButton' at 2;10.", repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButtonInfo, new RecordItemIndex(3));
            repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton.Click("2;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem2' at 227;4.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem2Info, new RecordItemIndex(4));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem2.Click("227;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea' at 199;12.", repo.DictionaryPropertiesBaseForm.TextEditorEditAreaInfo, new RecordItemIndex(5));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea.Click("199;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello' with focus on 'DictionaryPropertiesBaseForm.TxtDictName'.", repo.DictionaryPropertiesBaseForm.TxtDictNameInfo, new RecordItemIndex(6));
            repo.DictionaryPropertiesBaseForm.TxtDictName.PressKeys("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonEditorDropdownButton1' at 6;5.", repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton1Info, new RecordItemIndex(7));
            repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton1.Click("6;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem0' at 116;6.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem0Info, new RecordItemIndex(8));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem0.Click("116;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonOK' at 5;12.", repo.DictionaryPropertiesBaseForm.ButtonOKInfo, new RecordItemIndex(9));
            repo.DictionaryPropertiesBaseForm.ButtonOK.Click("5;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SYSTRANDictionaryManager.NumberOfEntries1'.", repo.SYSTRANDictionaryManager.NumberOfEntries1Info, new RecordItemIndex(10));
            Validate.Exists(repo.SYSTRANDictionaryManager.NumberOfEntries1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.Close' at 24;11.", repo.SYSTRANDictionaryManager.CloseInfo, new RecordItemIndex(11));
            repo.SYSTRANDictionaryManager.Close.Click("24;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hello.ButtonNo' at 21;8.", repo.Hello.ButtonNoInfo, new RecordItemIndex(12));
            repo.Hello.ButtonNo.Click("21;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
